apiVersion: v1
kind: Service
metadata:
  name: falcaoit-ghost-blog
  labels:
    infra.cognod.es/service: falcaoit-ghost-blog

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 2368
      protocol: TCP
      name: ghost
  externalIPs:
    - 67.207.73.50
  selector:
    infra.cognod.es/service: falcaoit-ghost-blog
